homeassistant:
  # Name of the location where Home Assistant is running
  name: Olliff Home
  # Location required to calculate the time the sun rises and sets
  latitude: 34.185655
  longitude: -80.989215
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 106
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include customizations.yaml

sensor: !include sensors.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
   api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

isy994:
  host: http://192.168.15.55:80
  username: admin
  password: !secret isy_password
  hidden_string: '{HIDE}'

group: !include group_config.yaml

google:
  client_id: 811003481298-4gsuhta10evrgepn3nu4lpos7noo4jpr.apps.googleusercontent.com
  client_secret: !secret google_password

