default_view:
  view: yes
  entities:
    - group.wunderground
    - group.locks
    - group.lights
    - group.fans
    - group.calendar
    - sun.sun
    - sensor.speedtest_ping
    - sensor.speedtest_download
    - sensor.speedtest_upload

living_room_view:
  name: Living Room
  view: yes
  entities:
    - group.living_room_lights

master_bedroom_view:
  name: Master Bedroom
  view: yes
  entities:
    - group.master_bedroom

darksky_view:
  name: Darksky Weather
  view: yes
  entities:
    - group.darksky

darksky:
  name: Darksky Weather
  entities:
    - sensor.dark_sky_summary
    - sensor.dark_sky_icon
    - sensor.dark_sky_precip
    - sensor.dark_sky_precip_intensity
    - sensor.dark_sky_precip_probability
    - sensor.dark_sky_temperature
    - sensor.dark_sky_wind_speed
    - sensor.dark_sky_cloud_coverage
    - sensor.dark_sky_humidity
    - sensor.dark_sky_visibility
    - sensor.dark_sky_minutely_summary
    - sensor.dark_sky_hourly_summary
    - sensor.dark_sky_daily_summary
    - sensor.dark_sky_daily_high_temperature
    - sensor.dark_sky_daily_low_temperature

wunderground:
  name: Weather Underground
  entities: 
    - sensor.weather_underground_pws
    - sensor.pws_stationid
    - sensor.pws_observation_time
    - sensor.pws_location
    - sensor.pws_elevation
    - sensor.pws_weather
    - sensor.pws_temp_f
    - sensor.pws_feelslike_f
    - sensor.pws_uv
    - sensor.pws_relative_humidity
    - sensor.pws_wind_degrees
    - sensor.pws_wind_string
    - sensor.pws_dewpoint_string
    - sensor.heat_index_string
    - sensor.pws_precip_1hr_in
    - sensor.pws_precip_today_in
    - sensor.pws_wind_mph
    - sensor.pws_wind_dir
    - sensor.pws_visibility_mi
    - sensor.pws_alerts

#   Fahrenheit/Imperial
#    - sensor.pws_dewpoint_f
#    - sensor.pws_temp_f
#    - sensor.pws_feelslike_f
#    - sensor.heat_index_f
#    - sensor.pws_wind_mph
#    - sensor.pws_wind_gust_mph
#    - sensor.pws_precip_1hr_in
#    - sensor.pws_precip_today_in
#    - sensor.pws_pressure_in
#    - sensor.pws_visibility_mi

#   Celsius/Metric
#    - sensor.pws_dewpoint_c
#    - sensor.pws_temp_c
#    - sensor.pws_feelslike_c
#    - sensor.pws_heat_index_c
#    - sensor.pws_wind_kph
#    - sensor.pws_wind_gust_kph
#    - sensor.pws_precip_1hr_metric
#    - sensor.pws_precip_today_metric
#    - sensor.pws_pressure_mb
#    - sensor.pws_visibility_km

locks: 
  name: Locks
  entities:
    - lock.front_door_lock
    - lock.garage_door_lock

lights:
  name: Lights
  entities:
    - switch.living_room_lamp
    - light.loveseat_lamp
    - light.brians_corner_lamp
    - light.foyer_light
    - light.mbr__nightstand_lamps
    - switch.front_door__porch_light

fans:
  name: Ceiling Fans
  entities:
    - switch.mbr_ceiling_fan    

living_room_lights:
  name: Lights
  entities:
    - switch.living_room_lamp
    - light.loveseat_lamp
    - light.brians_corner_lamp

master_bedroom:
  name: Master Bedroom
  control: hidden
  entities:
    - switch.mbr_ceiling_fan
    - light.mbr__nightstand_lamps

calendar:
  name: Calendar
  entities:
    - sensor.family_calendar_message
    - sensor.family_calendar_location
    - sensor.family_calendar_start_time
    - sensor.holiday_message
